### ISSUE TITLE
Ground truth

### ISSUE THREAD

**Issue by srn284** [blei-lab/causal-text-embeddings#4]
Dear @vveitch and Team, 
Re the paper, I had a question for the ground truth values in table 2 for confounding low med high. I was wondering how ground truth is calculated and if so, what methods of verification/robustness checking are endorsed for measurements of ground truth?

Thank you very much.
Warm wishes,
Shishir

**Comment by vveitch** [comment]
Hi,

The ground truth here is known in table 2 because the data is semi-synthetic. We simply simulate both the factual and counterfactual outcomes for each unit and then compute their mean difference :)

**Comment by srn284** [comment]
Dear Victor,
Many apologies for the late reply - was buried with something unavoidable in the last week.
Thank you very much for the response! I get what you’re saying now about how we know it’s ground truth and the value is ATE naive without any of the other stats estimators. 

Much appreciated Victor! :)
Thank you,
Shishir

**Comment by vveitch** [comment]
Glad that cleared it up :)
